#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_HOME=$(cd "${0%/*}" && pwd -P)
GRADLE_BIN=/c/Users/Jeiheewon/.gradle/wrapper/dists/gradle-8.13-bin/5xuhj0ry160q40clulazy9h7d/gradle-8.13/bin/gradle
export GRADLE_USER_HOME=/c/Users/Jeiheewon/.gradle
PROJECT_CACHE_DIR=/c/Users/Jeiheewon/.gradle/regret-diary-project-cache

exec "$GRADLE_BIN" --project-cache-dir "$PROJECT_CACHE_DIR" -p "$APP_HOME" "$@"
